services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: epic_lab_order_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: